s="Rank 1"
r="First Rank"
print(s + r)
print(s>"first")
print(s=='rank 1')
print(s[:1]+s[-1:])
print(r[4::-1])
print(s.isalpha())
print(s.isalnum())
print(s.istitle())
print(r.istitle())
print(r.title())
print(r.capitalize())
print(r.swapcase())
print(r.find('r'))
print(r.find('r',3))
print(r.count('r'))
print(r.partition('r'))
print(r.split('r'))
print(r.lstrip('RIFT'))
print(r.rstrip('kind'))
print(r.lower())
print(r.title())
print(r.capitalize())
print(r.swapcase())
print(r.find('r'))
print(r.find('r',3))
print(r.count('r'))
print(r.partition('r'))
print(r.split('r'))
print(r.lstrip('RIFT'))
print(r.rstrip('kind'))
